# For Airsim Dataset

# name of the sequence
seq_name: 'airsim'

# directories containing camera configs
# provide the absolute paths (i.e. /home/<name>/...) or relative paths with respect to this YAML file
camera_configs:
  - 'left_cam.yaml'
  - 'right_cam.yaml'